### ISSUE TITLE
Error on LASER() object creation

### ISSUE THREAD

**Issue by OpenSourceIronman** [ROBO-BEV/Tapomatic#13]
Hey @dull7295,

Why do I get the folllowing error when I try to create a LASER() object in the main function of LASER.py?

pi@raspberrypi:~/Tapomatic/v2020.0 $ python3 LASER.py 
DEBUG STATEMENTS ARE ON INSIDE LASER.py CLASS
LASER.py MESSAGE: Running LASER.py main unit test

Traceback (most recent call last):
  File "LASER.py", line 25, in <module>
    class LASER:
  File "LASER.py", line 302, in LASER
    TestLASERobject = LASER(RaspPi.BOARD7, "40004672601138", "205-0003-A", STANDARD_POWER, 10, COCOTAPS_LOGO)
NameError: name 'LASER' is not defined

**Comment by OpenSourceIronman** [comment]
Figured it out. The "class LASER:" and "7 if __name__ == "__main__":" lines of code need to have the same indentation amount (zero tabs in this case)
