### ISSUE TITLE
WHAT TYPE OF OBJECT DOES imread() TAKE???

### ISSUE THREAD

**Issue by OpenSourceIronman** [ROBO-BEV/Tapomatic#17]
Traceback (most recent call last):
  File "LASER.py", line 314, in <module>
    TestLASERobject = LASER(RaspPi.BOARD7, "40004672601138", "205-0003-A", LASER.STANDARD_POWER, 10, CocoDrink.COCOTAPS_LOGO)
  File "LASER.py", line 93, in __init__
    self.brandingArt = LASER.__WarpImage(LASER.LoadImage(CocoDrink.COCOTAPS_LOGO), CocoDrink.SIZE_102MM) # Initialize to standard CocoTaps logo
  File "LASER.py", line 142, in __WarpImage
    img = cv2.imread(currentImage)   #TODO WHAT TYPR OF OBJECT DOES imread() TAKE???
SystemError: <built-in function imread> returned NULL without setting an error

**Comment by OpenSourceIronman** [comment]
https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

**Comment by OpenSourceIronman** [comment]
It needs file path :)
